# Generated by Django 5.2.6 on 2025-09-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exists():
            return
        
        superuser = User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='password'
        )
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser),
    ]
